send_message:
    resource: "@SendMessageBundle/Resources/config/routing.yml"
    prefix:   /

list_message:
    resource: "@ListMessageBundle/Resources/config/routing.yml"
    prefix:   /

request:
    resource: "@RequestBundle/Resources/config/routing.yml"
    prefix:   /

