services:
      api.message.service:
        class: ApiBundle\Business\Service\ApiMessageService
        arguments: ["@message.service"]

      api.access.token.security.service:
        class: ApiBundle\Business\Service\AccessTokenSecurityService
        arguments: ["@doctrine.orm.entity_manager"]